spring:
  jpa:
    properties:
      hibernate:
        global_naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    open-in-view: false
